replicaCount: 1

deploymentName: 100jokes
serviceName: jokes

image:
  repository: lipudemoregistry.azurecr.io/100jokes
  pullPolicy: Always
  tag: latest
container:
  containerPort: 8080

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
