---
# Source: chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 100jokes
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: 100jokes
  template:
    metadata:
      labels:
        deployment: 100jokes
    spec:
      containers:
        - name: 100jokes
          image: "lipudemoregistry.azurecr.io/100jokes:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
