---
# Source: chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jokes
spec:
  selector: 
    deployment: 100jokes
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
