apiVersion: apps/v1
kind: Deployment
metadata:
  name: 100jokes
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: 100jokes
  template:
    metadata:
      labels:
        deployment: 100jokes
    spec:
      containers:
      - name: node-app
        image: lipu/100jokes:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080