kind: Service
apiVersion: v1
metadata:
  name: jokes
spec:
  selector:
    deployment: 100jokes
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP